apiVersion: v2
name: mastodon
description: Mastodon is a free, open-source social network server based on ActivityPub.
home: https://joinmastodon.org
maintainers:
  - name: Timothy Campbell
    email: tim@joinmastodon.org
    url: https://github.com/timetinytim
type: application
version: 0.1.10
appVersion: "v4.4.5"
