{{- if .Values.mastodon.hooks.dbPrepare.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mastodon.fullname" . }}-db-prepare
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
    {{- include "mastodon.jobUserLabels" . | trim | nindent 4}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
spec:
  template:
    metadata:
      name: {{ include "mastodon.fullname" . }}-db-migrate
      annotations:
        {{- include "mastodon.userJobAnnotations" . | trim | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: {{ include "mastodon.fullname" . }}-db-migrate
          {{- include "mastodon.container.specPreDeploy" . | trim | nindent 10 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - rake
            - db:prepare
          env:
            {{- include "mastodon.secrets.secret" (merge (dict "preDeploy" true ) .) | nindent 12 }}
            {{- include "mastodon.secrets.database" (merge (dict "preDeploy" true ) .) | nindent 12 }}
            {{- include "mastodon.secrets.redis" (merge (dict "preDeploy" true ) .) | nindent 12 }}
{{- end }}
