{{- if .Values.redis.sidekiq.enabled }}
{{- if not .Values.redis.sidekiq.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.redisSidekiqName" (merge (dict "preDeploy" true ) .) }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
type: kubernetes.io/basic-auth
data:
  password: {{ required "Redis sidekiq password is required with no existing secret" .Values.redis.sidekiq.password | b64enc }}
{{- end }}
{{- end }}
