{{- if .Values.mastodon.streaming.extraCerts.caCert }}
{{- if not .Values.mastodon.streaming.extraCerts.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.streamingCertName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.mastodon.streaming.extraCerts.caCert | b64enc }}
{{- end }}
{{- end }}
