{{- if not .Values.externalAuth.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.externalAuth.oidcName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: Opaque
data:
  client-id: {{ required "OIDC client ID is required with no existing secret" .Values.externalAuth.oidc.clientId | b64enc }}
  client-secret: {{ required "OIDC client secret is required with no existing secret" .Values.externalAuth.oidc.clientSecret | b64enc }}
{{- end }}
