apiVersion: v2
name: fediscoverer
description: Exploring decentralized search and discovery for the Fediverse.
home: https://discovery.joinmastodon.org
maintainers:
  - name: Mastodon
    url: https://joinmastodon.org
icon: https://avatars.githubusercontent.com/u/24979032
type: application
version: 0.2.0
appVersion: "v0.1.0"
